mpc:
  horizon: 30
  simulation_mode: 2 # 1 one-time simulation, 2 closed loop simulation 
  loop_size : 5000 # number of MPC loops to be executed in closed loop simulation, use infinity for entire driving cycle
  number_of_iterations: 100
  run_times: 1

unconstrained_solver:
  type: "GN"        # GN/LV/DL

linear_solver:
  type: 1  # 0 eigenumfpacklu, 1 EigenPardisoLU, 2 EigenLU, 3 EigenLDLT, 4 EigenQR, 5 EigenDensePartialLU,
           # 6 EigenDenseFullLU, 7 EigenDenseQR, 8 EigenSVD, 9 EigenBiCGSTAB, 10 EigenLSCG, 11 CSparse, 12 Cholmod,
             
                            
 
inequality_algorithm: "ispd"   # "al" or "bipm" or "ispd"
equality_algorithm: "gn"       # "gn" or "al" 

general_settings:
  verbose: 0
  max_num_inner_iterations:  5
  lagrange_multiplier_initial_eq: 0.0
  rho_initial_eq: 0.5
  rho_min_eq: 0.55
  rho_max_eq: 5e5
  rho_update_factor_eq: 20

#al_ineq_settings: use same for the equality


bipm_settings:
  kappa0: 0.2
  t_final: 1500.0
  nu: 8.0

ispd_settings: 
  linear_system_strategy: 0 # 0:ISPD, 1: barrier-slack 2: PD 3: BIPM 
  step_size_strategy: 0 # 0:  min(ineq_step,aux_step), 1: average(ineq_step,aux_step), 2: ineq_step, 3: aux_step 4: constant = 1.0

  ineq_backtracking_step_min: 10e-1
  aux_backtracking_step_min: 8e-1
  
  _init_kappa_strategy: 0 # constant  = _kappa0, 1: based on duality gap
  kappa_initial: 1e-3
  update_kappa_strategy: 0 # 0:check if t>=t_memory, 1: check if t>=_kappa0;  2: accept what comes from the duality gap; 3: by fixed nu
  nu: 15.0
  kappa_final: 1500.0
  tau: 1.4 # factor to increase t based on previous t value if _update_kappa_strategy ==0
  limit_kappa_final: 1 # (bool) limit kappa to kappa_final

  init_slack_strategy: 0 # 0: max(-g(x0),_slack_variable_initial_ineq, 1: max(abs(g(x0)),_slack_variable_initial_ineq,  2: constant  = _slack_variable_initial_ineq
  slack_variable_initial_ineq: 10.0 
  
  init_lagrange_strategy: 0 #  0:  _lagrange_multiplier_initial_ineq 1: max(1/(kappa0*slack),_lagrange_multiplier_initial_ineq) kappa0,
  lagrange_multiplier_initial_ineq: 10.0
  

  ineq_prediction_strategy: 0   #  0: g(x) + error_prediction* step_size *J*delta x , 1: g(x+ error_prediction_step_size *  delta x)
  ineq_prediction_step_strategy: 0 # 0: step_size = 1, 1: step_size = ineq_prediction_param, 2: _ineq_step 3:_ineq_step * ineq_prediction_param
  ineq_prediction_param: 1.0 # must be in (0,1]

  keep_aux_positive_strategy: 0 # 0: scaling of the potential variables, 1: correction to positive value using aux_correction_value 2: both absolute Inequality and auxiliary variables are kept positive using backtracking
  aux_scaling_factor: .2
  aux_correction_value: 1e0

  feas_tol: 1e-3




acc_settings: 
  spaceDomain: 1 # 0: time domain, 1: space domain
  linearDynamics: 0 # 0: off, 1: on
  linearInequalities: 0 # 0: off, 1: on 
  scaleInequalities : 0 # 0: off, 1: onineq_prediction_param
  ampl_solver:  5 # 0: ipopt, 1: knitro with alg 1, 2: knitro with alg 2, 3: knitro with alg 3,
                 # 4: knitro with alg 4, 5: conopt, 6: loqo, 7: minos, 8: snopt, 9: bonmin, 
                 # 10: couenne, 11: highs, 12: scip, 13: gcg, 14: cbc, 15: gurobi, 16: xpress, 
                 # 17: cplex, 18: copt, 19: mosek, 20: baron, 21: lgo, 22: lindoglobal
                  # 23: knitro with alg 1 no presolved, 24: knitro with alg 4 no presolved
                 # 99 make loop from 0 to 8 and print results for all solvers
  
  
  